export const TEMPLATE_LIST = 'ARTICLE_LIST'
export const TEMPLATE_ADD = 'ARTICLE_ADD'
export const TEMPLATE_UPDATE = 'ARTICLE_UPDATE'
export const TEMPLATE_REMOVE = 'ARTICLE_REMOVE'

export default {
  TEMPLATE_LIST,
  TEMPLATE_ADD,
  TEMPLATE_UPDATE,
  TEMPLATE_REMOVE,
}